version: '3.1'

services:
  db:
   image: postgres
   environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: root
        POSTGRES_DB: employeemanagement
   ports:
      - "5432:5432"



